helloworld: helloworld.c
	gcc helloworld.c -S -fno-asynchronous-unwind-tables -O0

basic: basic.c
	gcc basic.c -S -fno-asynchronous-unwind-tables -O0

empty: empty.c
	gcc empty.c -S -fno-asynchronous-unwind-tables -O0

empty64: empty64.c
	gcc empty64.c -S -fno-asynchronous-unwind-tables -O0