helloworld: helloworld.c
	gcc helloworld.c -S -fno-asynchronous-unwind-tables -O0

basic: basic.c
	gcc basic.c -S -fno-asynchronous-unwind-tables -O0

empty: empty.c
	gcc empty.c -S -fno-asynchronous-unwind-tables -O0

empty64: empty64.c
	gcc empty64.c -S -fno-asynchronous-unwind-tables -O0

duplicate: duplicate.c
	gcc duplicate.c -S -fno-asynchronous-unwind-tables -O0

params: params.c
	gcc params.c -S -fno-asynchronous-unwind-tables -O0

convert: convert.c
	gcc convert.c -S -fno-asynchronous-unwind-tables -O0

arith: arith.c
	gcc arith.c -S -fno-asynchronous-unwind-tables -O0

var: var.c
	gcc var.c -S -fno-asynchronous-unwind-tables -O0

loop: loop.c
	gcc loop.c -S -fno-asynchronous-unwind-tables -O0